name: Setup Swift
description: Setup Swift environment and restore SPM cache

runs:
  using: composite
  steps:
    - name: Cache SPM dependencies
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('Package.swift', 'Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
